export enum EVENT_TOPICS {
    ADMIN_LOGIN = 'ADMIN_LOGIN',
    ADMIN_SIGNUP = 'ADMIN_SIGNUP',
    ADMIN_CREATE_ROLE = 'ADMIN_CREATE_ROLE',
    ADMIN_UPDATE_ROLE = 'ADMIN_UPDATE_ROLE',
    ADMIN_GET_ROLES = 'ADMIN_GET_ROLES',
    REGISTER_AGENCY_QUERY = 'REGISTER_AGENCY_QUERY',
    CREATE_AGENCY = 'CREATE_AGENCY',
    UPDATE_AGENCY = 'UPDATE_AGENCY',
    DELETE_AGENCY = 'DELETE_AGENCY',
    ADMIN_GET_ROLE_BY_ID = 'ADMIN_GET_ROLE_BY_ID',
    CREATE_SUPER_ADMIN = 'CREATE_SUPER_ADMIN'
}
