export enum EVENT_TOPICS {
    ADMIN_LOGIN = 'ADMIN_LOGIN',
    ADMIN_SIGNUP = 'ADMIN_SIGNUP',
    ADMIN_CREATE_ROLE = 'ADMIN_CREATE_ROLE',
    ADMIN_UPDATE_ROLE = 'ADMIN_UPDATE_ROLE',
    ADMIN_GET_ROLES = 'ADMIN_GET_ROLES',
}
